language: ruby
rvm:
  - 2.2
  - ruby-head
env:
  - DB=postgresql
sudo: false
before_install:
  - gem install bundler
  - "rm ${BUNDLE_GEMFILE}.lock"
before_script:
  - psql -c 'create database registry_test;' -U postgres
  - psql -c 'create database registry_whois_test;' -U postgres
  - psql -c 'create database registry_api_log_test;' -U postgres
  - bundle update
  - cp config/application-example.yml config/application.yml
  - cp config/database-travis.yml config/database.yml
  - RAILS_ENV=test bundle exec rake db:all:schema:load
  - RAILS_ENV=test bundle exec rake db:seed
script: 
 - RAILS_ENV=test bundle exec rake
cache: bundler
services:
  - postgresql
addons:
  postgresql: "9.3"
