language: ruby
cache: bundler
env:
  - DB=postgresql
bundler_args: --without development staging production
before_script:
  - "psql -c 'create database registry_test;' -U postgres"
  - "psql -c 'create database registry_whois_test;' -U postgres"
  - "psql -c 'create database registry_api_log_test;' -U postgres"
  - "cp config/application-example.yml config/application.yml"
  - "cp config/secrets-example.yml config/secrets.yml"
  - "cp config/database-travis.yml config/database.yml"
  - "RAILS_ENV=test bundle exec rake db:setup:all"
script:
  - "RAILS_ENV=test bundle exec rspec"
after_success:
  - "bundle exec codeclimate-test-reporter"
services:
  - postgresql
addons:
  postgresql: "9.4"
  code_climate:
branches:
  only:
    - master
    - staging
