language: ruby
env:
  - DB=postgresql
bundler_args: --without development staging production
before_script:
  - "psql -c 'create database registry_test;' -U postgres"
  - "psql -c 'create database registry_whois_test;' -U postgres"
  - "psql -c 'create database registry_api_log_test;' -U postgres"
  - "cp config/application-example.yml config/application.yml"
  - "cp config/secrets-example.yml config/secrets.yml"
  - "cp config/database-travis.yml config/database.yml"
  - "RAILS_ENV=test bundle exec rake db:all:create"
  - "RAILS_ENV=test bundle exec rake db:all:schema:load"
  - "RAILS_ENV=test bundle exec rake db:migrate"
script:
  - "RAILS_ENV=test bundle exec rspec"
services:
  - postgresql
addons:
  postgresql: "9.4"
  code_climate:
      repo_token: 2fd0ab95eab718206f6732fdbd7b650da1e228f8dd491ef2082bb59d8684a054
branches:
  only:
    - master
    - staging
