language: ruby
rvm:
  - 2.4
  - 2.5
  - 2.6
cache: bundler
env:
  - DB=postgresql
bundler_args: --without development staging production
before_install:
  - "wget -N http://chromedriver.storage.googleapis.com/2.43/chromedriver_linux64.zip -P ~/"
  - "unzip ~/chromedriver_linux64.zip -d ~/"
  - "rm ~/chromedriver_linux64.zip"
  - "sudo mv -f ~/chromedriver /usr/local/share/"
  - "sudo chmod +x /usr/local/share/chromedriver"
  - "sudo ln -s /usr/local/share/chromedriver /usr/local/bin/chromedriver"
  - "gem update --system"
  - "gem install bundler"
before_script:
  - "cp config/application-example.yml config/application.yml"
  - "cp config/database-travis.yml config/database.yml"
  - "bundle exec rake db:setup:all"
  - "curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter"
  - "chmod +x ./cc-test-reporter"
  - "./cc-test-reporter before-build"
script:
  - "bundle exec rspec"
  - "bundle exec rake test"
after_script:
  - "./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT"
services:
  - postgresql
addons:
  postgresql: "9.4"
  chrome: stable
