language: ruby
cache: bundler
env:
  - DB=postgresql
bundler_args: --without development staging production
before_script:
  - "psql -c 'create database registry_test;' -U postgres"
  - "psql -c 'create database registry_whois_test;' -U postgres"
  - "psql -c 'create database registry_api_log_test;' -U postgres"
  - "cp config/application-example.yml config/application.yml"
  - "cp config/database-travis.yml config/database.yml"
  - "bundle exec rake db:setup:all"
  - "curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter"
  - "chmod +x ./cc-test-reporter"
  - "./cc-test-reporter before-build"
script:
  - "bundle exec rake test"
  - "bundle exec rspec"
after_script:
  - "./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT"
services:
  - postgresql
addons:
  postgresql: "9.4"
