default: &default
  host: localhost
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: test
  password: test

test:
  <<: *default
  database: registry_test

whois_test:
  <<: *default
  database: registry_whois_test

api_log_test:
  <<: *default
  database: registry_api_log_test

production:
  <<: *default
  database: registry_test

whois_test:
  <<: *default
  database: registry_whois_test

api_log_test:
  <<: *default
  database: registry_api_log_test
